config/routes.rb
Rails.application.routes.draw do

	devise_for :users, path: '', path_names: {sign_in: 'login', sign_out: 'logout', sign_up: 'register'}

	resources :contacts
	resources :users

	root to: "contacts#index"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < ApplicationRecord
	validates_presence_of :name, :seniority, :type_work, :location, :specialty, :linkedin, :added_by
	has_many :specialties
end

app/models/skill.rb
class Skill < ApplicationRecord
end

app/models/specialty.rb
class Specialty < ApplicationRecord
  belongs_to :contact
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController

	def index

		@type_work = Contact.select(:type_work).map(&:type_work).uniq
		@seniority = Contact.select(:seniority).map(&:seniority).uniq
		@location = Contact.select(:location).map(&:location).uniq

	    if current_user

	    	tw = params[:type_work]
	    	sr = params[:seniority]
	    	lt = params[:location]

	    	if (tw && sr && lt) 
			    @contact_entries = Contact.where(type_work:tw).where(seniority:sr).where(location:lt)
			elsif (tw && sr) 
			    @contact_entries = Contact.where(type_work:tw).where(seniority:sr)
			elsif (tw && lt) 
			    @contact_entries = Contact.where(type_work:tw).where(location:lt)
			elsif (sr && lt) 
			    @contact_entries = Contact.where(seniority:sr).where(location:lt)
			elsif (tw) 
			    @contact_entries = Contact.where(type_work:tw)
			elsif (sr) 
			    @contact_entries = Contact.where(seniority:sr)
			elsif (lt) 
			    @contact_entries = Contact.where(location:lt)
			else
			    @contact_entries = Contact.all 
	    	end

		else
	        redirect_to new_user_session_path
		end
	end

	def show
	   @contact_entries = Contact.find(params[:id])
	end

	def new
		@contact_entries = Contact.new 
	end

	def create
	    @contact_entries = Contact.new(params.require(:contact).permit(:name, :seniority, :type_work, :location, :specialty, :linkedin, :added_by))

	    respond_to do |format|
	      if @contact_entries.save
	        format.html { redirect_to contacts_path, alert: 'The new marketer was successfully added' }
	      else
	        format.html { render :new }
	      end
	    end
	end

	def edit
		@contact_entries = Contact.find(params[:id])
	end

	def update
		@contact_entries = Contact.find(params[:id])

    	respond_to do |format|
      		if @contact_entries.update(params.require(:contact).permit(:name, :seniority, :type_work, :location, :specialty, :linkedin, :added_by))
        		format.html { redirect_to contact_path, alert: 'The record was successfully updated.' }
      		else
        		format.html { render :edit }
      		end
    	end
  	end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
end

app/controllers/sessions_controller.rb
class SessionsController < Devise::SessionsController
		layout "welcome"
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
  	@users = User.find(params[:id])
  	@contacts = Contact.where(added_by:params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

	def alerts
		alerts = (flash[:alert] || flash[:error] || flash[:notice])
		if alert 
			alert_generator alert
		end
	end

	def alert_generator msg
		js add_gritter(msg)
	end

end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/contacts/edit.html.erb
<main role="main" class="col-md-9 ml-sm-auto col-lg-10 px-4">

  <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
    <h1 class="h2">Edit this profile</h1>
    <div class="btn-toolbar mb-2 mb-md-0">
      <div class="btn-group mr-2">
        <button class="btn btn-sm btn-default"><%= link_to "Back", :back %></button>
      </div>
    </div>
  </div>

  <%= form_for(@contact_entries) do |form| %>
  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, class: 'form-control', placeholder: 'Name' %>
  </div>
  <br>
  <div class="field">
    <%= form.label :seniority %>
    <%= form.text_field :seniority, class: 'form-control', placeholder: 'Seniority' %>
  </div>
  <br>
  <div class="field">
    <%= form.label :type_work %>
    <%= form.text_field :type_work, class: 'form-control', placeholder: 'ype of Work' %>
  </div>
  <br>
  <div class="field">
    <%= form.label :location %>
    <%= form.text_field :location, class: 'form-control', placeholder: 'Location' %>
  </div>
  <br>
  <div class="field">
    <%= form.label :specialty %>
    <%= form.text_area :specialty, class: 'form-control', placeholder: 'Enter specialties separated by coma.
For example: SEO, SEM, FB Ads.' %>
  </div>
  <br>
  <div class="field">
    <%= form.label :linkedin %>
    <%= form.text_field :linkedin, class: 'form-control', placeholder: 'LinkedIn' %>
  </div>
  <br>
  <div class="field">
    <%= form.hidden_field :added_by %>
    <%= form.hidden_field :added_by, :value => current_user.id %>
  </div>
  <br>
  <div class="actions">
    <%= form.submit "Enter", class: 'btn btn-lg btn-primary' %>
  </div>
  <% end %>

</main>

app/views/contacts/index.html.erb
<main role="main" class="col-md-9 ml-sm-auto col-lg-10 px-4">
  <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
    <h1 class="h2">List of Talent</h1>
    <div class="btn-toolbar mb-2 mb-md-0">
    </div>
  </div>

  <div class="table-responsive">
    <table class="table table-striped table-sm text-center">
      <thead>
        <tr>
          <form method="GET" action="/">
            <th class="text-left">
              <h6>Name</h6>
            </th>
            <th>
              <h6>
                Type Work:

                <select name="type_work">
                  <option value="" disabled selected>All</option>
                  <% @type_work.each do |type_work| %>
                    <option value="<%= type_work %>" <%= type_work == params[:type_work] ? "selected" : "" %> ><%= type_work %></option>
                  <% end %>
                </select>
              </h6>
            </th>
            <th>
              <h6>
                Seniority:
                <select name="seniority">
                  <option value="" disabled selected>All</option>
                  <% @seniority.each do |seniority| %>
                    <option value="<%= seniority %>" <%= seniority == params[:seniority] ? "selected" : "" %> ><%= seniority %></option>
                  <% end %>
                </select>
                </h6>
            </th>
            <th>
              <h6>
                Location:
                <select name="location">
                  <option value="" disabled selected>All</option>
                  <% @location.each do |location| %>
                    <option value="<%= location %>" <%= location == params[:location] ? "selected" : "" %> ><%= location %></option>
                  <% end %>
                </select>
              </h6>
            </th>
            <th>
              <div class="btn-group" role="group">
                <input type="submit" class="btn btn-outline-dark" value="Filter"/>
                <a href="/" class="btn btn-outline-link">Clear</a>
              </div>
            </th>
          </form>
        </tr>
      </thead>
      <tbody>
        <% @contact_entries.each do |contact_entries| %>
          <tr>
            <td class="text-left"><%= link_to contact_entries.name, contact_path(contact_entries) %></td>
            <td><%= contact_entries.type_work %></td>
            <td><%= contact_entries.seniority %></td>
            <td><%= contact_entries.location %></td>
            <td>
              <button type="submit" class="btn btn-outline-success btn-sm">Recommend</button>
              <button type="submit" class="btn btn-outline-primary btn-sm">Bookmark</button>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</main>

app/views/contacts/new.html.erb
<main role="main" class="col-md-9 ml-sm-auto col-lg-10 px-4">

  <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
    <h1 class="h2">Add a Marketer</h1>
    <div class="btn-toolbar mb-2 mb-md-0">
      <div class="btn-group mr-2">
        <button class="btn btn-sm btn-default"><%= link_to "Back", :back %></button>
      </div>
    </div>
  </div>

  <%= form_for(@contact_entries) do |form| %>

    <div class="field">
      <%= form.label :name, class: 'sr-only'  %>
      <%= form.text_field :name, class: 'form-control', placeholder: 'Name', autofocus: true %>
    </div>
    <br>
    <div class="field">
      <%= form.label :seniority, class: 'sr-only'  %>
      <%= form.text_field :seniority, class: 'form-control', placeholder: 'Seniority' %>
    </div>
    <br>
    <div class="field">
      <%= form.label :type_work, class: 'sr-only'  %>
      <%= form.text_field :type_work, class: 'form-control', placeholder: 'Type of Work' %>
    </div>
    <br>
    <div class="field">
      <%= form.label :location, class: 'sr-only'  %>
      <%= form.text_field :location, class: 'form-control', placeholder: 'Location' %>
    </div>
    <br>
    <div class="field">
      <%= form.label :specialty, class: 'sr-only' %>
      <%= form.text_area :specialty, class: 'form-control', placeholder: 'Enter specialties separated by coma.
For example: SEO, SEM, FB Ads.' %>
    </div>
    <br>
    <div class="field">
      <%= form.label :linkedin, class: 'sr-only'  %>
      <%= form.text_field :linkedin, class: 'form-control', placeholder: 'LinkedIn' %>
    </div>
    <br>
    <div class="field">
      <%= form.hidden_field :added_by %>
      <%= form.hidden_field :added_by, :value => current_user.id %>
    </div>
    <br>
    <div class="actions">
      <%= form.submit "Enter", class: 'btn btn-lg btn-primary'%>
    </div>

  <% end %>
</main>

app/views/contacts/show.html.erb
<main role="main" class="col-md-9 ml-sm-auto col-lg-10 px-4">

	<div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
		<h1 class="h2"><%= @contact_entries.name %></h1>
		<div class="btn-toolbar mb-2 mb-md-0">
			<div class="btn-group mr-2">
				<button class="btn btn-outline-secondary btn-sm"><%= link_to "Edit", edit_contact_path %></button>
			</div>
			<div class="btn-group mr-2">
				<button type="submit" class="btn btn-outline-success btn-sm">Recommend</button>
			</div>
			<div class="btn-group mr-2">
				<button type="submit" class="btn btn-outline-primary btn-sm">Bookmark</button>
			</div>
			<div class="btn-group mr-2">
				<button class="btn btn-outline-link btn-sm"><%= link_to "Back", :back %></button>
			</div>
		</div>
	</div>

	<div>
		<h6>Profile</h6>
		<ul class="list-group">
		  <li class="list-group-item"><strong>Title:</strong> <%= @contact_entries.seniority %></li>
		  <li class="list-group-item"><strong>Type of work:</strong> <%= @contact_entries.type_work %></li>
		  <li class="list-group-item"><strong>Location:</strong> <%= @contact_entries.location %></li>
		</ul>
	</div>
	<br>
	<div>
		<h6>Specialties:</h6>
		<ul class="list-group">
		  <li class="list-group-item"><%= @contact_entries.specialty %></li>
		</ul>
	</div>
	<br>
	<div>
		<h6>Contact Details</h6>
		<ul class="list-group">
		  <li class="list-group-item"><strong>LinkedIn:</strong> <%= @contact_entries.linkedin %></li>
		  <li class="list-group-item"><strong>Added by:</strong> <%= @contact_entries.added_by %></li>
		</ul>
	</div>

</main>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>GcTalent</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <div class="container-fluid">
      <div class="row">

        <% if current_user %>
          <%= render "/shared/topbar" %>
          <%= render "/shared/sidebar" %>
        <% end %>

        <% if flash[:alert] %>
          <%= js add_gritter(flash[:alert]) %>
        <% elsif flash[:error] %>
          <%= js add_gritter(flash[:error]) %>
        <% else %>
          <%= js add_gritter(flash[:notice]) %>
        <% end %>

        <%= yield %>

      </div>
    </div>
  </body>
</html>

app/views/layouts/welcome.html.erb
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>GcTalent</title>

	<%= stylesheet_link_tag 'page_forms', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container-fluid">
      <div class="row">

      <%= yield %>

      </div>
    </div>
  </body>
</html>

app/views/shared/_alerts.html.erb
<% if flash[:alert] %>
  <%= js add_gritter(flash[:alert]) %>
<% elsif flash[:error] %>
  <%= js add_gritter(flash[:error]) %>
<% else %>
  <%= js add_gritter(flash[:notice]) %>
<% end %>

app/views/shared/_sidebar.html.erb
<nav class="col-md-2 d-none d-md-block bg-light sidebar">
  <div class="sidebar-sticky">
    <ul class="nav flex-column">
      <li class="nav-item">
        <%= link_to "Browse", root_path, class: 'nav-link' %>
      </li>
      <li class="nav-item">
        <%= link_to "Add Marketer", new_contact_path, class: 'nav-link' %>
      </li>
    </ul>
  </div>
</nav>

app/views/shared/_topbar.html.erb
<nav class="navbar navbar-dark fixed-top bg-dark flex-md-nowrap p-0 shadow">
  <a class="navbar-brand col-sm-3 col-md-2 mr-0" href="/">GC Talent</a>
  <input class="form-control form-control-dark w-100" type="text" placeholder="Search" aria-label="Search">
  <ul class="navbar-nav px-3">
    <li class="nav-item text-nowrap">
        <%= link_to "Profile", user_path(current_user), class: 'nav-link' %>
    </li>
  </ul>
</nav>

app/views/users/show.html.erb
<div class="container-fluid">
	<div class="row">

		<%= render "/shared/topbar" %>
		<%= render "/shared/sidebar" %>

		<main role="main" class="col-md-9 ml-sm-auto col-lg-10 px-4">

			<div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
				<h1 class="h2"><%= @users.email %></h1>
				<div class="btn-toolbar mb-2 mb-md-0">
					<div class="btn-group mr-2">
						<button class="btn btn-sm btn-default"><%= link_to "Back", :back %></button>
					</div>
					<div class="btn-group mr-2">
						<button class="btn btn-sm btn-outline-secondary"><%= link_to "Logout", destroy_user_session_path, class: 'nav-link', method: :delete %></button>
					</div>
				</div>
			</div>
			<br>

			<div>
				<h6>Contacts Added </h6>
				<ul class="list-group">
					<% @contacts.each do |c| %>
						<li class="list-group-item"><%= c.name %></li>
					<% end %>
				</ul>
			</div>

		</main>
	</div>
</div>